# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  imagename: 'image-$(Build.Repository.Name):(build.SourceBranchName)-$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image & deploy
  jobs:
  - job: Build
    displayName: Build & deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Container Registry'
        repository: 'Congre17'
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: '$$(Build.BuildId)'
      
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'Container Registry'
        repository: 'Congre17'
        command: 'push'
        Dockerfile: 'Dockerfile'
        tags: '$(Build.BuildId)'
        
      
    
